version: '3.8'
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment:
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #Needs to be fix, so that the miners know the resulting enode id
    build:
      context: ./bootnode
      args:
        binary: 1.10.2+build25719+xenial 
    ports:
      - 30301:30301/udp
    networks:
      chainnet:
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on

  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    depends_on:
      - geth-bootnode
    environment:
      - address=0x789eeac8071ce0faae85a97cdd83f4677524d74d #derived from the private key which is passed in the args
      - bootnodeId=4312022a6c7f8962220a039ce7656a1abfb54141ba554b50e1cc8d93487a80e67e7f1615f9be4389fdc3452684753401fbf4c3a6bb3e57c3ee9cbfe92a122b2e #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./miner
      args:
        binary: 1.10.2+build25719+xenial
        privatekey: 6208a98d1f31430fa51a37b89a0016b842d8570d7e3da0bac7ca5e11bc96b2f6 # Please don't do something like this in production, okay?
        password: vcn123
    container_name: geth-miner-1
    ports:
      - 8545:8545
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address

  geth-dev-miner-2:
    hostname: geth-dev-miner-2
    depends_on:
      - geth-dev-miner-1
    environment:
      - address=0x0e32574b1ea5280168916aae8c8ab330d836e5c8 #derived from the private key which is passed in the args
      - bootnodeId=4312022a6c7f8962220a039ce7656a1abfb54141ba554b50e1cc8d93487a80e67e7f1615f9be4389fdc3452684753401fbf4c3a6bb3e57c3ee9cbfe92a122b2e #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./miner
      args:
        binary: 1.10.2+build25719+xenial
        privatekey: 36d5f32dddc0097f3f895a0c4f42530a010c039bb003ff52c3f4b5984f8050ee
        password: word
    container_name: geth-miner-2
    ports:
      - 8546:8545
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
     - eth-data-2:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.104

  geth-dev-miner-3:
     hostname: geth-dev-miner-3
     depends_on:
       - geth-dev-miner-2
     environment:
       - address=0x1f2192fce51f9bd96a37a4df09af4791ab0d0916 #derived from the private key which is passed in the args
       - bootnodeId=4312022a6c7f8962220a039ce7656a1abfb54141ba554b50e1cc8d93487a80e67e7f1615f9be4389fdc3452684753401fbf4c3a6bb3e57c3ee9cbfe92a122b2e #derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./miner
       args:
         binary: 1.10.2+build25719+xenial 
         privatekey: 78df575164c9e31dc27c0ff059a3714dec2a99c91b07e2bd814c4f0356dfce51
         password: word
     container_name: geth-miner-3
     ports:
       - 8547:8545
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-data-3:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.110

  geth-monitor-backend:
    hostname: geth-monitor-backend
    depends_on:
      - geth-dev-miner-1
    build:
      context: ./monitor-backend
    container_name: monitor-backend
    networks:
      chainnet:

  geth-monitor-frontend:
   hostname: geth-monitor-frontend
   depends_on:
     - geth-monitor-backend
   build:
     context: ./monitor-frontend
   container_name: monitor-frontend
   ports:
    - 3000:3000
   networks:
    chainnet:
      ipv4_address: 172.25.0.103

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
  eth-data-2:
  eth-data-3:
